# Generated by Django 4.1.7 on 2023-03-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='is_published',
            new_name='is_publisher',
        ),
    ]
