# Generated by Django 4.1.7 on 2023-03-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_is_published_ad_is_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='is_publisher',
            new_name='is_published',
        ),
    ]
